version: "3.9"

services:
  api:
    image: kain1029/sghserver:latest
    build:
      context: .
      dockerfile: SGHServer.API/Dockerfile
    container_name: "API"
    ports:
      - "5000:80"
  apiTest:
    image: kain1029/sghserver:test
    build:
      context: .
      dockerfile: SGHServer.API/Dockerfile
    container_name: "API"
    ports:
      - "5001:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "SGHDatastore"
      POSTGRES_USER: "Server"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"